name = "medical-bot"
main = "index.js"
compatibility_date = "2025-04-15"

[[kv_namespaces]]
binding = "USER_STATES"
id = "f8a475d5ea614bc09db22077581e1fe6"

[vars]
BOT_TOKEN = "8330456846:AAFJFM3cy7rbKr5diPbcYi8QaIDDIhktpVU"
DB_HOST = "your-site.infinityfreeapp.com"
API_SECRET = "nadia"
