name = "medical-bot"
main = "index.js"
compatibility_date = "2025-04-15"

[[kv_namespaces]]
binding = "USER_STATES"
id = "YOUR_KV_ID"

[vars]
BOT_TOKEN = "8330456846:AAFJFM3cy7rbKr5diPbcYi8QaIDDIhktpVU"
DB_HOST = "your-site.infinityfreeapp.com"
API_SECRET = "nadia"
